name: unit-test smart contract
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: unit test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment
        uses: actions/setup-node@v3
      - name: Test
        run: |
          cd smart-contract
          npm i
          npx hardhat test
